// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqZhepkKzGaS8EgRhNUApvdBI8DRX5da0',
    appId: '1:52270552804:web:f28a6202efda6f90163ef1',
    messagingSenderId: '52270552804',
    projectId: 'vozletra-16bc9',
    authDomain: 'vozletra-16bc9.firebaseapp.com',
    storageBucket: 'vozletra-16bc9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHZWjlWwW_0jxQ24yeWnPCmaZzwDsREWs',
    appId: '1:52270552804:android:b8f07ef4d331bf82163ef1',
    messagingSenderId: '52270552804',
    projectId: 'vozletra-16bc9',
    storageBucket: 'vozletra-16bc9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmZyyk5ngXFMKHBNau1Ukwi5y7fV8An58',
    appId: '1:52270552804:ios:0d32beab9bce2a74163ef1',
    messagingSenderId: '52270552804',
    projectId: 'vozletra-16bc9',
    storageBucket: 'vozletra-16bc9.appspot.com',
    iosClientId: '52270552804-13nngancki2b5l7a377jvcr1d80vuca2.apps.googleusercontent.com',
    iosBundleId: 'com.example.speechoutApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmZyyk5ngXFMKHBNau1Ukwi5y7fV8An58',
    appId: '1:52270552804:ios:0d32beab9bce2a74163ef1',
    messagingSenderId: '52270552804',
    projectId: 'vozletra-16bc9',
    storageBucket: 'vozletra-16bc9.appspot.com',
    iosClientId: '52270552804-13nngancki2b5l7a377jvcr1d80vuca2.apps.googleusercontent.com',
    iosBundleId: 'com.example.speechoutApp',
  );
}
