// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPgN0p5MPR_9RD8PuSpPYopXMl3fwRvtU',
    appId: '1:624522877347:web:80059ddeddf68c0ab9a216',
    messagingSenderId: '624522877347',
    projectId: 'spell-out-f6f05',
    authDomain: 'spell-out-f6f05.firebaseapp.com',
    storageBucket: 'spell-out-f6f05.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLEwkTF3gyaW0rYDXJNCDVvvq44BZ-o50',
    appId: '1:624522877347:android:c1ffb7be1e452a5db9a216',
    messagingSenderId: '624522877347',
    projectId: 'spell-out-f6f05',
    storageBucket: 'spell-out-f6f05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaa2JhAdZ3ejOFqn4_GADePUM8QeLUMbE',
    appId: '1:624522877347:ios:d0b9529a5ec28f52b9a216',
    messagingSenderId: '624522877347',
    projectId: 'spell-out-f6f05',
    storageBucket: 'spell-out-f6f05.appspot.com',
    iosClientId: '624522877347-ub6flolv5avq1baf7fgdbh949eed13el.apps.googleusercontent.com',
    iosBundleId: 'com.example.speechoutApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaa2JhAdZ3ejOFqn4_GADePUM8QeLUMbE',
    appId: '1:624522877347:ios:d0b9529a5ec28f52b9a216',
    messagingSenderId: '624522877347',
    projectId: 'spell-out-f6f05',
    storageBucket: 'spell-out-f6f05.appspot.com',
    iosClientId: '624522877347-ub6flolv5avq1baf7fgdbh949eed13el.apps.googleusercontent.com',
    iosBundleId: 'com.example.speechoutApp',
  );
}
